apiVersion: apps/v1
kind: Deployment

metadata:
  name: quiz-api
  labels:
    app: quiz-api
    rel: stable

spec:
  replicas: 3
  selector:
    matchLabels:
      app: quiz-api
      rel: stable
  
  template:
    metadata:
      labels:
        app: quiz-api
        rel: stable
        ver: '0.1'
    spec:
      containers:
      - name: quiz-api
        image: jbetoreyes/quiz-api:0.1
        imagePullPolicy: Always
        env:
        - name: APP_PORT
          value: '8080'
        - name: DB_HOST
          value: mongo
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: password
        ports:
        - name: http
          containerPort: 8080
