apiVersion: apps/v1
kind: Deployment

metadata:
  name: quiz-api
  labels:
    app: quiz-api
    rel: stable

spec:
  selector:
    matchLabels:
      app: quiz-api
      rel: stable
  
  template:
    metadata:
      labels:
        app: quiz-api
        rel: stable
        ver: '0.1'
    spec:
      containers:
      - name: quiz-api
        image: jbetoreyes/quiz-api
        imagePullPolicy: Always
        env:
        - name: APP_PORT
          value: '8080'
        ports:
        - name: http
          containerPort: 8080
